### ISSUE TITLE
Intellij Idea Ultimate - missing on Marketplace

### ISSUE THREAD

**Issue by landsman** [jansorg/swift-plugin#17]
Hi Joachim,

first of all, thank you for this plugin! I was looking for it once I found that AppCode was terminated and there wasn't any. This is a great way how to let me partially use it in my favorite editor.

When I saw your comment in the article I immediately went to the editor to download the plugin, but there wasn't any result. I can not find it.

Do you have idea how to make it work thought the editor?

![Screenshot 2023-07-05 at 9 10 58](https://github.com/jansorg/swift-plugin/assets/3184228/6651b8c1-0ba4-44c2-a8ae-d36cfbb8214c)

![Screenshot 2023-07-05 at 9 15 41](https://github.com/jansorg/swift-plugin/assets/3184228/d188e885-db78-4f54-84b3-3f75b8279a24)

```
IntelliJ IDEA 2023.1.3 (Ultimate Edition)
Build #IU-231.9161.38, built on June 20, 2023
Licensed to Michal Landsman
Subscription is active until July 22, 2023.
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 8000M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    com.github.leomillon.uuidgenerator (4.5.1)
    net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)
    org.intellij.plugins.hcl (231.8109.91)
    com.intellij.apacheConfig (231.9161.47)
    org.jetbrains.plugins.localization (231.8109.91)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    org.jetbrains.plugins.ruby (231.9161.26)
    com.intellij.nativeDebug (231.8770.15)
    String Manipulation (9.9.0)
    CheckStyle-IDEA (5.81.0)
    ChatGPT (3.0.1-231)
    MavenRunHelper (4.23.222.2964.0)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    dev.blachut.svelte.lang (231.8770.15)
    com.dmarcotte.handlebars (231.8770.3)
    mdx.js (231.8109.91)
    com.dsoftware.ghtoolbar (1.13.1)
    org.intellij.scala (2023.1.19)
    mobi.hsz.idea.gitignore (4.5.1)
    com.github.codespaces.jetbrains.gateway (0.4.0.1262)
    com.intellij.spring.websocket (231.8770.17)
    com.intellij.spring.batch (231.8770.17)
    net.ashald.envfile (3.4.1)
    com.jetbrains.php (231.9161.47)
    izhangzhihao.rainbow.brackets (2023.2.11)
    com.jetbrains.twig (231.9161.47)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.annotation (9.4.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.253)

Kotlin: 231-1.8.21-IJ9161.38
```

**Comment by landsman** [comment]
I don't want to download it and install from file, because there will be no automatic updates I guess.

**Comment by landsman** [comment]
Oh sorry I totally missed required version `2023.2`. Do you plan to make it work on stable versions like `2023.1.3`?

**Comment by jansorg** [comment]
Thanks for your feedback!
Unfortunately, making it available for earlier versions would make it conflict with the existing Swift support and complicate things a lot. AFAIK the final 2023.2 will be available in about three weeks. I hope that this is a good enough compromise, as you should hopefully still have access to CLion+Swift with 2023.1.

**Comment by landsman** [comment]
I understand, thanks!
