### ISSUE TITLE
plugin doesn't recognize valid swift syntax

### ISSUE THREAD

**Issue by amijsul** [jansorg/swift-plugin#21]
This line  is causing the plugin to error

```swift
func testConditional(error: Error) -> Bool {
        return error is Error ? true : false
}
``` 

It appears that it can't handle an is check as a conditional

**Comment by jansorg** [comment]
Thanks! I've fixed this for the next update.
It was a problem with the parsing of optional types (`Error?` is an optional type, `Error ?` is not)
