### ISSUE TITLE
SwiftUI some View not working

### ISSUE THREAD

**Issue by avinizhanov** [jansorg/swift-plugin#22]
```
var label: some View {
    Label(rawValue.capitalized, systemImage: self.icon)
}
```

This has error:

```
',', '.', <, <raw value style enum member>, <union style enum member>, '=', '{' or '}' expected, got 'View'
```

<img width="833" alt="Screenshot 2023-08-29 at 10 06 44 AM" src="https://github.com/jansorg/swift-plugin/assets/42622715/0a2d104f-2310-4747-b5e3-6fa6af916e3c">

Plugin version: 0.16.0.121-232

**Comment by jansorg** [comment]
Thanks, that's very helpful! This is fixed for the next update, which should be available tomorrow or Thursday
