### ISSUE TITLE
Property wrapper with parameters not working

### ISSUE THREAD

**Issue by avinizhanov** [jansorg/swift-plugin#23]
This one causing error:

```
@Environment(\.scenePhase) var scenePhase
```

```
';', <compiler control statement>, <deinitializer declaration>, <import declaration>, <operator declaration>, '@', precedencegroup or '}' expected, got '@'
```
![Screenshot 2023-08-31 at 8 28 19 AM](https://github.com/jansorg/swift-plugin/assets/42622715/5aaefd0e-85d2-47f7-8900-98e8890affc5)

Property wrapper without parameters works fine, for example:

```
@State var test: Bool = false
```

Plugin version: 0.17.0.123-232

**Comment by jansorg** [comment]
Thanks! I've fixed this for the next update.
